# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Gabriel Heming
email: gabriel.heming@hotmail.com
description: >- # this means to ignore newlines until "baseurl:"
    Entusiasta da programação orientada à objetos e seus respectivos padrões e princípios.
    Sempre de olho em novas tecnologias e desafios.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gabrielheming.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
bitbucket_username: gabrielheming
github_username: gabrielheming
#linkedin_username: gabriel-bertolini-heming

bitbucket-perfil: https://bitbucket.org/gabrielheming/
github-perfil: https://github.com/gabrielheming/
linkedin-perfil: https://www.linkedin.com/in/gabriel-bertolini-heming/
imasters-perfil: https://forum.imasters.com.br/profile/159859-gabriel-heming/
stack-overflow-perfil: https://pt.stackoverflow.com/users/5007/gabriel-heming

just_comments:
    api_key: 8c6f3597-bb2d-4c50-a5ca-2bf0f6c5e030

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

google_analytics: UA-99026779-2
timezone: America/Sao_Paulo
